app/__init__.py
from flask import Flask, render_template
from .main import main as main_blueprint

def page_not_found(e):
    return render_template('404.html'), 404

def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'secret'
    app.register_blueprint(main_blueprint)
    app.register_error_handler(404, page_not_found)
    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views

app/main/views.py
from functools import wraps
from flask import render_template, session, redirect, url_for, request, flash
from . import main

from ..fb_functions import create_user, login_with_email_password, verify_id_token

# LoginRequired Decorator
def login_required(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        print("im gay")
        uid = session.get('uid')
        if uid is None:
            flash("You need to login first")
            return redirect(url_for('main.login'))
        return f(*args, **kwargs)
    return decorated_function


@main.route('/')
def index():
    return render_template('index.html')

@main.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form['email']
        password = request.form['password']
        # Call login_with_email_password function
        token = login_with_email_password(email, password)
        if token:
            # Store the token in the session
            uid = verify_id_token(token)
            session['uid'] = uid
            return redirect(url_for('main.index'))
        else:
            flash("Invalid Credentials")
            return redirect(url_for('main.login'))
    return render_template('login.html')

@main.route('/signup', methods=['GET', 'POST'])
def signup():
    if request.method == 'POST':
        email = request.form['email']
        name = request.form['name']
        password = request.form['password']
        license_no = request.form['license']
        contact = request.form['contact']
        create_user(email, password, name, license_no, contact)
        return redirect(url_for('main.login'))
    return render_template('signup.html')

@main.route('/uid')
def return_uid():
    uid = session.get('uid')
    return f"UID: {uid}"

@main.route('/logout')
@login_required
def logout():
    session.pop('uid', None)
    return redirect(url_for('main.index'))

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Invoice Tracker</title>
    <!-- Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <link href="{{url_for('static', filename='styles.css')}}" rel="stylesheet">
</head>
<body>
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Invoice Tracker</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Features</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Pricing</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
                </li>
            </ul>
        </div>
    </nav>

    <!-- Main Content -->
    <div class="container">
        
    </div>

    <!-- Bootstrap JS and dependencies -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

app/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Invoice Tracker & Generator</title>
    <link rel="stylesheet" href="{{url_for('static', filename='styles.css')}}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
    <div class="container-fluid">
        <div class="container">
            <div>
                <h1 class="text-center title">Invoice Generator & Tracker</h1>
                <div class="row">
                    <div class="col auth-btn">
                        <a href="{{ url_for('main.login') }}" class="btn btn-primary btn-lg">Login</a>
                        <a href="{{ url_for('main.signup') }}" class="btn btn-primary btn-lg">Register</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
</body>
</html>

app/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Invoice Tracker & Generator</title>
    <link rel="stylesheet" href="{{url_for('static', filename='styles.css')}}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
        <div class="container">
            <div>
                {% with messages = get_flashed_messages() %} 
                    {% if messages %}
                        <ul class="flashes list-group">
                            {% for message in messages %}
                            <li class="list-group-item">
                                <div class="alert alert-success">{{message}}</div>
                            </li>
                            {% endfor %}
                        </ul>
                    {% endif %} 
                {% endwith %}
            </div>
            <div class="card auth-card">
                <form class="card-body" action="{{ url_for('main.login') }}" method="post">
                    <div class="mb-3 auth-field">
                        <label for="email" class="form-label">Email address</label>
                        <input name="email" type="email" class="form-control" id="email" required>
                        <div class="form-text">We'll never share your email with anyone else.</div>
                    </div>
                    <div class="mb-3 auth-field">
                        <label for="password" class="form-label">Password</label>
                        <input name="password" type="password" class="form-control" id="password" required>
                    </div>
                    <div class="mb-3 auth-field">
                        <button type="submit" class="btn btn-primary">Login</button>
                    </div>
                    <div class="mb-3 auth-field">
                        <p>Don't have an account? <a href="{{ url_for('main.signup') }}">Register</a></p>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
</body>
</html>

app/templates/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Invoice Tracker & Generator</title>
    <link rel="stylesheet" href="{{url_for('static', filename='styles.css')}}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
        <div class="container">
            <div class="card auth-card">
                <div class="card-body">
                    <h3 class="mb-3">Sign Up</h3>
                    <form action="{{ url_for('main.signup') }}" method="post">
                        <div class="mb-3">
                            <input type="email" name="email" class="form-control" placeholder="Email" required>
                        </div>
                        <div class="mb-3">
                            <input type="text" name="name" class="form-control" id="name" placeholder="Name" required>
                        </div>
                        <div class="mb-3">
                            <input type="text" name="license" class="form-control" id="license" placeholder="License No" required>
                        </div>
                        <div class="mb-3">
                            <input type="text" name="contact" class="form-control" id="contact" placeholder="Phone No" required>
                        </div>
                        <div class="mb-3">
                            <input type="password" name="password" class="form-control" id="password" placeholder="Password" required>
                        </div>
                        <div>
                            <input class="btn btn-primary" type="submit" value="Sign Up">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
</body>
</html>